"""Application-level encryption for secrets stored in Postgres (spec §6.2).

Used for `gemini_api_keys.encrypted_key`. The plan allows Supabase Vault or
application-level AES-GCM; this is the latter, so the capability to decrypt
lives only in the FastAPI process holding `MASTER_ENCRYPTION_KEY` and never in
the database itself.

AES-256-GCM: authenticated, so a tampered ciphertext fails to decrypt rather
than yielding garbage that gets sent to Google as an API key. Every encryption
uses a fresh random 96-bit nonce — reusing a nonce under GCM is catastrophic,
which is why the nonce is generated here and never passed in by a caller.

Stored form: ``v1.<base64url(nonce)>.<base64url(ciphertext||tag)>``. The version
prefix exists so a future key rotation or algorithm change can be detected
rather than guessed at.
"""

from __future__ import annotations

import base64
import hashlib
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

SCHEME = "v1"
NONCE_BYTES = 12
_KEY_BYTES = 32


class EncryptionError(RuntimeError):
    """Raised when a secret cannot be encrypted or decrypted.

    Deliberately carries no ciphertext, key material or plaintext in its
    message — this string reaches the logs.
    """


def _derive_key(master_key: str) -> bytes:
    """Stretch the configured master key to exactly 32 bytes.

    SHA-256 rather than a KDF with a salt: the input is a high-entropy value
    generated by `secrets.token_urlsafe(32)`, not a human-chosen password, so
    there is nothing for a slow KDF to defend against. A salt would also have
    to be stored alongside every ciphertext to be usable.
    """
    if not master_key:
        raise EncryptionError("MASTER_ENCRYPTION_KEY is not configured.")
    return hashlib.sha256(master_key.encode("utf-8")).digest()[:_KEY_BYTES]


def _b64e(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64d(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value + padding)


def encrypt_secret(plaintext: str, master_key: str | None) -> str:
    """Encrypt a secret for storage. Returns the versioned stored form."""
    if not plaintext:
        raise EncryptionError("Refusing to encrypt an empty secret.")
    aesgcm = AESGCM(_derive_key(master_key or ""))
    nonce = os.urandom(NONCE_BYTES)
    ciphertext = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)
    return f"{SCHEME}.{_b64e(nonce)}.{_b64e(ciphertext)}"


def decrypt_secret(stored: str, master_key: str | None) -> str:
    """Decrypt a stored secret.

    Raises `EncryptionError` on a wrong master key, a tampered ciphertext, or a
    malformed stored value — all indistinguishable to a caller on purpose.
    """
    try:
        scheme, nonce_b64, ciphertext_b64 = stored.split(".", 2)
    except ValueError as exc:
        raise EncryptionError("Stored secret is malformed.") from exc

    if scheme != SCHEME:
        raise EncryptionError(f"Unsupported encryption scheme: {scheme!r}.")

    aesgcm = AESGCM(_derive_key(master_key or ""))
    try:
        plaintext = aesgcm.decrypt(_b64d(nonce_b64), _b64d(ciphertext_b64), None)
    except (InvalidTag, ValueError, TypeError) as exc:
        raise EncryptionError(
            "Secret could not be decrypted; the master key may be wrong or the "
            "value may have been tampered with."
        ) from exc
    return plaintext.decode("utf-8")


def mask_secret(plaintext: str, *, visible: int = 4) -> str:
    """Last `visible` characters only (spec §6.3).

    Short values are masked entirely rather than partially revealed.
    """
    if len(plaintext) <= visible:
        return "*" * len(plaintext)
    return plaintext[-visible:]
