"""Alembic environment.

The URL comes from `core.config.Settings`, not from `alembic.ini`, so a
migration can never run against a different database than the application -
and no credential is committed.

Runs the migration through the async engine, because `models/orm.py` uses
`pgvector.sqlalchemy.Vector` and the asyncpg dialect; sharing one engine
configuration keeps offline SQL generation and online migration identical.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from core.config import get_settings
from db.base import Base
from db.session import normalise_database_url

# Importing the package registers every table on Base.metadata; without it
# autogenerate would happily emit a migration that drops the entire schema.
import models  # noqa: F401  isort: skip

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

_settings = get_settings()
if not _settings.database_url:
    raise RuntimeError(
        "DATABASE_URL is not set. Alembic reads it from the application settings "
        "so migrations cannot run against a different database than the API."
    )

_url, _connect_args = normalise_database_url(_settings.database_url)
config.set_main_option("sqlalchemy.url", _url.replace("%", "%%"))


def _configure(connection: Connection | None = None, **kwargs: object) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Type and server-default comparison off by default in Alembic; without
        # them an autogenerated revision silently misses a column widening or a
        # changed default.
        compare_type=True,
        compare_server_default=True,
        include_schemas=False,
        **kwargs,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a DBAPI connection (`alembic upgrade --sql`)."""
    _configure(
        url=config.get_main_option("sqlalchemy.url"),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args=_connect_args,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
