"""Declarative base and shared column mixins.

The naming convention matters more than it looks: without it, Alembic emits
`op.drop_constraint(None, ...)` for unnamed constraints and autogenerated
downgrades are not runnable. Declaring it once here means every index, unique
constraint, check and foreign key gets a deterministic name from the first
migration onward.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated in Postgres, not in Python.

    `gen_random_uuid()` (pgcrypto, built into Postgres 13+) means a row
    inserted by a migration, a seed script or psql gets an id on the same
    terms as one inserted by the API.
    """
    return mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """`created_at` / `updated_at` stamped by the database clock.

    Server-side defaults rather than Python defaults: an audit timestamp that
    depends on the application server's clock is not trustworthy across
    replicas, and spec §11 requires the trail to be non-forgeable.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CreatedAtMixin:
    """`created_at` only - for append-only tables that are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
